### ISSUE TITLE
Just use fetch here...

### ISSUE THREAD

**Issue by kriskuiper** [robert-hoekstra/functional-programming#3]
Why import a 238472937kb framework for just doing something that's already in the browser

https://github.com/robert-hoekstra/functional-programming/blob/f91c1e480d32e280d83837a4ef819ba729d303ce/javascript/app.js#L64-L69

**Comment by robert-hoekstra** [comment]
Because the purpose of this project is to work with D3 to visualize data. So the package needs to be included anyways.
