### ISSUE TITLE
Clean up folder structure

### ISSUE THREAD

**Issue by kriskuiper** [robert-hoekstra/functional-programming#4]
Looking very messy right now:

Could do something like:

* public
  * index.html
  * styles
    * app.css
* src
  * app.js

And use a bundler like [Rollup](https://rollupjs.org/guide/en/) or [Parcel](https://parceljs.org/) to bundle your javascript. You can then also use import and export to im- and export js files. Keeps your code modular and easier to follow/read.

**Comment by robert-hoekstra** [comment]
thanks. fixed it. Also live version can be found on Github pages now
