### ISSUE TITLE
We're living in 2019

### ISSUE THREAD

**Issue by kriskuiper** [robert-hoekstra/functional-programming#9]
So you could write this more functional by using array.map:

```js
array.map(item => {
  return {
    title: item.cho && item.cho.value // < first check if it has a cho, if so, return the value, otherwise die
    // . .... etc
  }
})
```

https://github.com/robert-hoekstra/functional-programming/blob/f91c1e480d32e280d83837a4ef819ba729d303ce/javascript/app.js#L77-L89

**Comment by kriskuiper** [comment]
The `&&` is to prevent 'Cannot read property value of undefined' errors

**Comment by robert-hoekstra** [comment]
I am not used to arrow-functions. Will consider it when I take the step from ES5 to ES6
